networks:
  default:
    name: tecnofit
    external: false

x-database-variables: &database-variables
  DB_HOST: db
  DB_PORT: 3306
  DB_DATABASE: tecnofit
  DB_USERNAME: root
  DB_PASSWORD: root

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
    environment:
      <<: *database-variables
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: db
    environment:
      <<: *database-variables
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tecnofit
    ports:
      - 3306:3306
    volumes:
      - ./mnt:/var/lib/mysql
      - ./database/Migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 30s

  seeds:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seeds
    working_dir: /var/www/html
    environment:
      <<: *database-variables
    volumes:
      - ./:/var/www/html
    command: php database/seeds.php
    depends_on:
      db:
        condition: service_healthy
